### ISSUE TITLE
The docker image is broken.

### ISSUE THREAD

**Issue by sylv** [sylv/micro#15]
It seems prisma doesn't want to play nice so the decision is between a ~700mb docker image with dev dependencies or ditch prisma. `typed-knex` might be worth considering. For now the `:latest` docker image is fine, `:master` is built automatically and won't start because the prisma client isn't generated.

**Comment by Likqez** [comment]
~ 700mb would be unconvinient to create/push and pulling/using on consumer side. I guess it would be better to ditch it :)

**Comment by sylv** [comment]
I'm still working on the image size, which is something ridiculous like 1.4gb at the moment. Probably gonna ditch nextjs in the future and see if i can compile it all to a single binary or something, ideally it would be ~300mb total.
