### ISSUE TITLE
Obsidian not embedding uploads

### ISSUE THREAD

**Issue by cykreet** [sylv/micro#43]
Obsidian does not seem to embed micro urls, the upload itself works fine when visiting directly.

Tested with the following:
```
![](https://cyk.needs-a-hug.co/i/UJcbUb.png)
```
![image](https://github.com/sylv/micro/assets/45258926/3dce38a6-4af9-4612-8b02-9e5d290e97cb)

**Comment by sylv** [comment]
Tried getting this working, I'm 95% sure it's a bug with obsidian. Those URLs are returning plain images with no funky business, and if you create a canvas and paste it in there it works so it seems to be a weird bug with notes...?

I also tried getting embedded URLs working but obsidian sends a normal browser `User-Agent` so nothing can be done about it.
