### ISSUE TITLE
docker compose databases connection error

### ISSUE THREAD

**Issue by maxcutie** [sylv/micro#6]
currently facing this issue when trying to run docker compose

any ideas how to fix? ;-;

![error](https://i.imgur.com/kFNMsBu.png)

**Comment by sylv** [comment]
Pretty sure your connection URI for postgres is wrong, if you're using the docker-compose file from `/examples` it should be `postgresql://micro:youshallnotpass@postgres/micro`. Might also be affected by the outdated docker image because the build is failing but I'll fix that in a minute.

**Comment by maxcutie** [comment]
ah okay ill try and see if that fixes it

thank you for the fast reply <3

**Comment by sylv** [comment]
I added some updated installation instructions which should hopefully work. Once the new Docker image is pushed you can try with the new examples and installation instructions if you didn't figure it out.

**Comment by maxcutie** [comment]
alright i'll give it a look. few you a few dollars on patreon for your help <3

**Comment by maxcutie** [comment]
everything is looking good but im getting a new error which is confusing me. 

i replaced the DATABASE_URL field with "postgresql://micro:youshallnotpass@postgres/micro" but it's still returning this error.

dont know if im retarded or dumb

![image](https://user-images.githubusercontent.com/30512573/113644160-f48abc80-9638-11eb-8218-2c053eaffcfe.png)
![image](https://user-images.githubusercontent.com/30512573/113644206-11bf8b00-9639-11eb-9ab3-2d671bcdf45b.png)

**Comment by sylv** [comment]
Ooooh yeah I might have overlooked that. If you're doing the prisma migration try `docker-compose run -e DATABASE_URL=postgresql://micro:youshallnotpass@postgres/micro micro prisma db push --preview-feature`, that should let it pick up the database URL.

**Comment by maxcutie** [comment]
I feel so bad spamming you with all this 

`
Error: P1001: Can't reach database server at `postgres`:`5432`

Please make sure your database server is running at `postgres`:`5432`.
ERROR: 1
`

**Comment by sylv** [comment]
If I bothered testing the instructions you wouldn't have to so it's fine. Do `docker-compose up -d postgres` so the database is running while you run the migration, that should fix it.

**Comment by maxcutie** [comment]
worked ^_^

ur a lifesaver

**Comment by sylv** [comment]
epic. if you find other problems open another issue 👈🤠👈
